### ISSUE TITLE
main.b0a6984b.chunk.css empty by default?

### ISSUE THREAD

**Issue by squiggg** [bsides/horizoverlay#109]
This may be more of an issue on my end personally or with ACT but, for a few weeks now, the OverlayPlugin Horizoverlay preset has had an empty main.b0a6984b.chunk.css file, displaying this:
![image](https://user-images.githubusercontent.com/20999179/92809827-f9c9a680-f38a-11ea-96ff-cbaa630f9b62.png)

I can fix it by simply copying and pasting the text from the main.b0a6984b.chunk.css file using Chrome dev tools on https://bsides.github.io/horizoverlay/ but it eventually resets itself to being the blank css for some reason.

**Comment by bsides** [comment]
Hi @squiggg,

Something external is erasing your file - the file is intact as you can see here https://bsides.github.io/horizoverlay/static/css/main.b0a6984b.chunk.css

I know you already know this but that's something really hard to debug since it's coming from outside. I'll try to check it out this weekend but no promises. If anyone could help I'd appreciate. Meanwhile please check your setup again please.

**Comment by squiggg** [comment]
Yeah, I figured it wasn't an issue with Horizoverlay itself but I decided to be thorough about solving it and go in order of Horizoverlay -> OverlayPlugin -> ACT  and checking things on my end along the way. Feel free to close this without comment if you don't find anything ^^

**Comment by bsides** [comment]
Hey @squiggg we squashed some bugs recently, could you check if it's fixed? If not feel free to reopen the issue. Thank you!
