### ISSUE TITLE
Custom colors?

### ISSUE THREAD

**Issue by SillyShinyDragoon** [bsides/horizoverlay#116]
An option to set custom colors for each role (or heck even class) would be neat!

**Comment by bsides** [comment]
I agree! Hopefully someone could open a PR for it!

**Comment by Brafficus** [comment]
Hello, I'd like to work on this, I'm just having some issues testing locally.  I installed yarn and ran the following commands from within the cloned repository:

```
yarn
yarn build
yarn serve build
```

I'm serving build since that seemed to be where the actual output of ```yarn build``` was going (file creation dates were correct there and not docs), but when I try to set ACT to http://localhost:5000 (as mentioned in your instructions and shown in the console for ```yarn serve```), nothing shows up.  This is even the case when I try to serve docs, so I'm thinking that there's something wrong with my local environment but I haven't had any luck figuring out what it might be.  Do you happen to have any ideas?  I'd love to get to work on this and see if I can include it for everyone!

**Comment by Brafficus** [comment]
Disregard the above.  Not sure if this is intended or not, but I ran it using ```npm start``` and pointing ACT at http://localhost:3000/horizoverlay instead.  I'll get started on this now.

**Comment by Enubia** [comment]
> 
> 
> Disregard the above. Not sure if this is intended or not, but I ran it using `npm start` and pointing ACT at http://localhost:3000/horizoverlay instead. I'll get started on this now.

that's also what i did, are you now working on the custom colors? If you need help let me know, I'll go through the list of open issues and takle some other ones :D

**Comment by Brafficus** [comment]
> 
> that's also what i did, are you now working on the custom colors? If you need help let me know, I'll go through the list of open issues and takle some other ones :D

Yes, I'll be working on this feature for right now (trying to get accustomed to React since I'm used to Angular), then I'll likely look at a couple other open issues afterwards.  Thanks for the offer, I'll let you know if I need any help!
