### ISSUE TITLE
Overlay resets when someone LBs

### ISSUE THREAD

**Issue by vocruen** [bsides/horizoverlay#20]
Hello! 

This is a newer issue I noticed after the recent update where someone can LB, anyone really, and it will completely reset the overlay. But not just reset it, as in reset the instance, but the people who are considered "active" disappear and you only see the Boss + group DPS + time bar. 

Also, is there any chance you can keep the "Send to Discord" as an option and not just be default in the overlay?

**Comment by bsides** [comment]
Hi @vocruen, thanks for this report. I also noticed people missing and didn't know the limit break was the issue, but now that you mention, I do believe it is. Did you notice people resetting any other time around? This is a hard-to-catch bug andI'm inclined in removing limit break altogether again 😞 

Discord option was optional but somehow it's displaying even with the field in blank... I wonder why it's happening.

I rolled back the older version (2.1.2, before Discord feature) until this get fixed. Sorry for the trouble! 😅

**Comment by vocruen** [comment]
No problem! I was worried about reporting "too soon" because of my last report, and was worried that I might be bugging you. But I really like your overlay and helps out a lot when when I'm running Savage. But no, I have not seen it reset any other time. I think I noticed it because of the fact that I do run Savage frequently, and I've only seen it disappear when someone in the party LBs.

I wouldn't mind if you removed the Limit Break all together, but is there no way for you to put it in the same bar as the group DPS? Maybe like in-between group DPS and the time? The LB isn't super important but it's still nice to see. I like the idea of not having it with the other "active" sources.

I wish I knew how to code to help you out with this. But yeah, it's definitely weird that the Discord option setting isn't appearing.

Also, I did open up to have #21 so I will be testing both :D

**Comment by bsides** [comment]
I'm going to star by clearing I'm sorry if my answer in the other issue gave the impression I wasn't grateful for the opened issue @vocruen. Even if it's considered a duplicate for me, sometimes it's not obvious nor written anywhere so there's no way to tell, right? I'm just too objective sometimes and I often forget to discuss further.

Nothing is dumb or rushed around here, you're truly free to add an issue to ask a question, to report weird behavior, to anything you think could improve the theme.

About the problem: I made some tests with limit break and I think I used wrong calls there, but the thing is hard to test because it isn't easy get a lb data all the time heh. Regardless I already found what would probably be the error so I'll throw a new version soon in tests to check it.

Thanks again for taking your time to write here and let me know you care. I'll try to keep the changes in test environment documented soon too.

**Comment by bsides** [comment]
EDIT: I just uploaded a new version in the test URL, if you see any problem there please let me know. Me and @tiagofox are testing it too.

**Comment by bsides** [comment]
Ops, sorry, I want to see if you can test before I close this

**Comment by bsides** [comment]
@vocruen I'm considering this fixed, if you see anything weird please reopen or open another issue, ok? Thanks again!
