### ISSUE TITLE
What a lovely and amazing overlay! Are you interested in translate this into Chinese?

### ISSUE THREAD

**Issue by yorushika** [bsides/horizoverlay#29]
Hey there, sorry to disturb your life.
I'm a Chinese player&developer. Nice to meet you.
As mentioned in title, I like this overlay so much, so I installed this one into my  ACT and also, I am thinking of translating this overlay into Chinese and let other Chinese player get known of this awesome overlay!
So could you please allow me to cooperate with you for translation stuff?

Looking for your precious reply, thanks!

**Comment by bsides** [comment]
Hi @jeremiahshi nice to meet you!

Sure thing you can translate it. It would be my pleasure to help. Right now all the strings are hardcoded wouldn't be better to separate them?

I'm not playing right now in a PC so I have no way to test it but I could do that separation and I believe it would work just fine.

Please tell me if there's anything else I could do.

Good luck regardless, thanks and enjoy it 👍

**Comment by jeremiahshi** [comment]
Well I'll give it a shot~

I gonna clone one to local and try to translate strings. Perhaps combing with font adjustment for current font isn't suitable for Chinese characters' appearance.

On the other hand, there may be a bug causing local using unavailable now. Maybe I need to fork one to my own repos, setting it private and try to load online for debugging, if you permit.

I'll contact with you with every process. Thank you again for your kindness!

**Comment by yorushika** [comment]
Some issues here:
How did you deploy the overlay to Pages or other similiar service?
After several trying, I still cannot deploy it without any bugs, which contains JS cannot loaded and config window enabled by right-click appears nothing, etc.
I believe this is because wrong deployment, but I have no idea how to fix it. So can you help me out? qwq

**Comment by bsides** [comment]
Hi @yorushika!
Sorry for the delay in answering, I've been working a lot.

Yes you can fork it and change as you like. If you want, after translating and making your changes, tell me where is the version you want me to check and I'll do it. I don't know Chinese but I know where the strings are so I could help you with that.

Also I searched a better way to do it but it'd require a time that I unfortunately do not have right now. What we need is a change in config component to change the language and then pass this prop to the components that are being translated. It isn't hard, just require time.

To deploy, I'm using http://now.sh - it's terrific. I think there are some files to deploy straight tot it, let me check... Yes, I believe these commands in `package.json` are the right ones
https://puu.sh/zNsTQ/7ec60e0d38.png

I believe npm run now would do it all. I think you'll need a now account though. Tell me if I can help. I'm getting some time off this weekend so I could check it out.

**Comment by bsides** [comment]
Hi @yorushika thanks for the kind words!
Are you working on it? Im back to the game 😸 so if you need anything let me know!

**Comment by bsides** [comment]
@yorushika I just made a build with a translator.

Could you please test? Go to config and toggle "Language" to see it.
https://build-chhgevdmet.now.sh

Right now it has 2 languages, English and Portuguese, but you could easily add your own or send it to me so I can insert into the project. I separated it into another branch because I want to check out if everything I did works well before releasing to public so if you want to translate the file, just grab it from the branch locale: https://github.com/bsides/horizoverlay/blob/locale/src/locale.js

As you can see everything is there to translate, just copy and paste the `enUS` json and translate the strings. If there's any other string you think should be translated let me know so I can include in that file.

Thanks again!

**Comment by yorushika** [comment]
Hey, surely I’m catching up, but these days I have lots of work also coming with overtime. So did not have enough time for overlay recently. I’ll check it out today.

On the other hand, you are in Brazil, right? So we have 13-hour time lagging...emm whatever, I’ll do my best.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by yorushika** [comment]
Hey~

I have to say it’s a quite nice decision you made that using locale.js. Yes, it’s really convenience. I found same thing appeared in another overlay named MopiMopi<https://github.com/HAERUHAERU/mopimopi>(for WebSocket, not OverlayPlugin) , and also I made a translated version<https://gitlab.com/yorushika/ACT.WebSocket.Overlay.MopiMopi>, though the author didn’t reply my email ☹. I thought to tell you to use this way but I was sooooo busy at that moment, sorry!

All in all I tested the overlay in locale brunch and all functions seemed to be working well. Sol I added Simplified Chinese and Traditional Chinese into the overlay and tested on local, for I cannot find a free platform to deploy nodejs apps(now.sh is not available because I have not activate my credid card and it only supports credit card paying method). So I commited to the repo<https://github.com/yorushika/horizoverlay/tree/locale> I forked, in locale branch. I hope you can test it out in your side. If no issues appear I hope you can add these two languages into your main overlay!

Also, here’s a nice Chinese font, I think you can add it into overlay, for the default font Droid doesn’t support Chinese characters. I thought to add this into the code but after thinking I believe it’s better to let you do this modification XD.

Here’s the url: https://www.dropbox.com/sh/mqqo1erc4fw62cp/AACFKTNMkfxLttRjvMy2ZS8Va?dl=0
Both ttf and woff provided, woff works well on MopiMopi mentioned above.
I think you can open this link smoothly for dropbox was not blocked at your country(China has GFW ☹).
If there are any other ideas, I’m looking forwad to more communication😊.

I think you are sleeping now, NITE~

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by bsides** [comment]
Hey @yorushika! How are you?

Do you know how to open a Pull Request here in GitHub? Could you open a pull request with your changes into my repository, at branch locale? If you don't know how to do it let me know.

About the font, I'll certainly include it as an option as well. If the user select chinese as their language, those 2 fonts will appear as options, if not I could add some other fonts to the pack. One question though: **are these fonts free for public use?** I ask it because I don't want problems with the law. I already downloaded them.

About now.sh, they have a free plan. I don't pay for it and I dont remember it requiring a credit card. Check out their website: https://zeit.co/pricing, the OSS (Open Source Software) plan, it's completely free! Also, the only reason I'm using it is because I need https protocol and unfortunately at the time GitHub didn't have it. Right now I'm trying to get a HTTPS from here to move things out of there (although publishing by just typing `now build --public` is very nice).

If you want to use now, just install it https://zeit.co/download (if you want, install only the CLI version), go to your terminal and in the horizoverlay folder, type:
`yarn build`
`now build --public`
The first command will make a build in the build folder (it will create it if it doesnt exist). The second command publishes it in a url. If you have any errors with the second command, remove the files `.map` from the build/assets folder. They are big and useless for the build itself. Then try `now build --public` again. You will have an url to test it on ACT!

If you can't do a Pull Request please let me know so I can do it manually here.

Thanks again for all your efforts!!! I really appreciate it <3

**Comment by yorushika** [comment]
Hey there!

Gladly I can reply to you now!

The font is free to use, you can relax~ The repo is at https://github.com/be5invis/Sarasa-Gothic and the other is a Chinese font developer in Microsoft. These fonts are popular among Chinese developers.

I’ll make a pull request now. I have not tried to do this but I believe it won’t be complicated. Wait for a sec!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by yorushika** [comment]
Wrong typing, not “other” but “author”, XD.

I’ll check now.sh, too, thanks for your kindness~

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by bsides** [comment]
I consider this done as PR #31 
Thanks again @yorushika !!!

**Comment by yorushika** [comment]
You’re welcome.

Hope to see it at main page soon so I can introduce this overlay to my friends, XD.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by bsides** [comment]
Do you want to translate the main page too?

https://github.com/bsides/horizoverlay/blob/master/README.md

I could insert a link in this Markdown file to the chinese version and vice versa 👍

**Comment by yorushika** [comment]
Of corse! Gladly to!

发自我的 iPhone

在 2018年4月6日，06:44，Rafael Pereira <notifications@github.com<mailto:notifications@github.com>> 写道：


Do you want to translate the main page too?

https://github.com/bsides/horizoverlay/blob/master/README.md<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbsides%2Fhorizoverlay%2Fblob%2Fmaster%2FREADME.md&data=02%7C01%7C%7Ca5be3e765ddf4462319108d59b46d786%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636585650927782571&sdata=NxFs%2BWKZkAIzlYN31m%2BYvWInBwBeytW8plMB9DJkYjA%3D&reserved=0>

I could insert a link in this Markdown file to the chinese version and vice versa 👍

**Comment by bsides** [comment]
Hi @yorushika ! Everything is on the master branch now, so you could just use the main url ```https://horizoverlay.now.sh```

Hopefully the font is working too! It's a little big (20+mb) so if it doesn't appear right away it's because it's still downloading. Overall I think it's fine though.

Thanks again for doing all this! I'm going to update the README.md in the homepage thanking you :+1:

**Comment by bsides** [comment]
Hi @yorushika how are you?

I'm in the way of rewritting this whole overlay and I noticed the chinese font we used is really hard to build it in my new system. Is there any other font from [Google Web Fonts](https://fonts.google.com/) you would recommend? This way would be a lot easier to bundle it!

Thank you in advance!

**Comment by bsides** [comment]
PS - I thought Noto Sans would be really good. Would you agree?
