### ISSUE TITLE
Little advice

### ISSUE THREAD

**Issue by wingchaos** [bsides/horizoverlay#53]
A. supports ActWebScoket

B. adds a button to stop encounter 

C. hasn't thought well yet

LOL

**Comment by bsides** [comment]
Hi @wingchaos!
Sure thing I will implement it in the next few days. Thanks for posting 👍

**Comment by bsides** [comment]
Hey @wingchaos could you explain suggestion A for me? I'll try to implement B this weekend 👍

**Comment by EvilSakray** [comment]
A. is kinda already done @bsides 
You just need to have references to the ACT WebSocket scripts urls (maybe jquery as well) on your parser html layout in the head section:

```html
<head> 
[...]
<script src="https://ZCube.github.io/ACTWebSocket/Sample/actwebsocket.js"></script>
<script src="https://ZCube.github.io/ACTWebSocket/Sample/actwebsocket_compat.js"></script>
[...]
</head>
```

See: https://github.com/ZCube/ACTWebSocket 

I don't think it requires anything more from you. 

Then users need to have the actual ACTWebSocket plugin to make use of it.
However if you host the overlay **yourself** with ActWebSocket on a server that obviously supports websocket, it means people will be able to send their fight data to your server which might generate trafic you don't want.

Haeru overlay supports it for instance:
``http://haeru.xyz/index.html?HOST_PORT=ws://[Local IP:Port of the server ACTWebSocket plugins creates]``

This is mainly used for people streaming (they can easily capture the overlay into their stream using a BrowserSource that renders a web page instead of using Monitor Capture and such, which is pretty bad for performances)

Hope I managed to be clear :cry:

**Comment by bsides** [comment]
Awesome @EvilSakray, it made perfect sense. I'll look more into them today. Also, I always wanted to stream with the parser too, thanks for sharing it!

**Comment by bsides** [comment]
Hi @EvilSakray, I tried to implement it but I don't think it's working. I'll look more into it. Right now the JS are there (and throwing some errors) but I could just put it inside my build to fix it (to transform new js to old js).

**Comment by bsides** [comment]
It's definitely not working. I would need an example of implementation because those JavaScript are just samples and they don't tell much of how the plugin works. @HAERUHAERU code is very long so it's being a little hard to find where it is so maybe I could ask him for some advice. I'll let you know whenever it's ready.

**Comment by ZCube** [comment]
I add reverse proxy for github.io
You can use it likes http://localhost:10501/github/bsides/horizoverlay with ACTWebSocket 1.3.3.2
So I'll close https://github.com/ZCube/ACTWebSocket/issues/21

**Comment by EvilSakray** [comment]
@bsides Thanks I'll give it a try when I'm back from holidays.

**Comment by EvilSakray** [comment]
Sorry for the late reply:
![Sample](https://i.imgur.com/t9wxdBf.png)

The lowest dps is rank 1 on the far left and highest rank 8 on the far right.. it should be the opposite?
It might come from how I configured ACT itself though, but unsure where to change that.

**Comment by NearAutomata** [comment]
@bsides Sorry to hijack this issue but I guess it's the right spot to ask for help with ACTWebSocket. I have setup ACTWebSocket and can access the parser in the browser via `http://rafaelp.com.br/horizoverlay/?HOST_PORT=ws://[::1]:10501/#/`. Unfortunately there are two issue:

1. At the end of an encounter the DPS bar completely disappears and the page turns empty which is really not expected. When running the parser in the OverlayPlugin it works as expected.
2. Are the any ways to pass options to the page? I wanted to use the URL as a Browser Source in OBS for streaming, however I cannot change the options when embedding the page in my stream.

**Comment by EvilSakray** [comment]
@NearAutomata As i'm also using browser source in OBS; i'll try answering D;

1. Not sure, I thought the dps bar disapearing to only leave the area / fight length / raid dps was actually a feature. Unless you got nothing to show at all anymore once out of a fight, in which case I've got no clue. As far as I'm concerned, the area information bar being pretty transparent, i actually changed the css background-color of it through OBS itself since it lets you do so.

2. You can configure the overlay first in OBS by setting this url in the BrowserSource first: http://rafaelp.com.br/horizoverlay/#/config
Then right click the source and pick "Interact" to be able to set it up as you wish.
Settings will be saved if you keep the same source and just change the url back to
http://rafaelp.com.br/horizoverlay/?HOST_PORT=ws://[::1]:10501/#/ once you're done.

**Comment by NearAutomata** [comment]
@EvilSakray 
1. In my case all combatants are disappearing and I have the location/target/duration bar disabled anyways. I don't know whether it's a feature or not but I dislike that everything disappears at the end of an encounter. If it's a feature, there should be an option to toggle that behaviour in the first place. Furthermore I stumbled upon even more bugs like combatants being in the opposite order or Limit Break not appearing in the list but still preventing the last (or first) combatant to be visible.
2. That feature seems to be what I am looking for but it hasn't been implemented in Streamlabs OBS yet. Therefore i have to wait for it.

**Comment by bsides** [comment]
Sorry for the very late reply, I'll look more into it in the next version of the overlay. For now, if you need anything (or the questions above are still valid) let me know in another issue, please.

Thanks again for bringing me this!
