### ISSUE TITLE
24-man issue

### ISSUE THREAD

**Issue by Khallenis** [bsides/horizoverlay#88]
Hello, really like the hud, it's clean.

I like to leave displaying only 8 people, since I mainly use it for 8-man content. However, now with the new NieR raid (and even before 24-man from roulettes) it doesn't display the top 8 DPS, it shows only the bottom 8 DPS.

When I change the config to show all 24 people, it display fine, but when you start to reduce the display number, it get to eat the top DPS always. Tryed to change ACT "sort type" setting, but didn't got any luck.

Is there any solution on my end or is something that I'll have to live with it?

![image](https://user-images.githubusercontent.com/57275306/68062235-d7d1b300-fce7-11e9-9157-c999dee2ae60.png)

**Comment by bsides** [comment]
Hi @Khallenis!

Just out of curiosity, did you adjust your FFXIV Plugin in ACT to measure Alliance and up?

Regardless of the answer above, I need to get this a try but I don't really know how to test it... I'm going to try it with a test file but it can take a while since I'm not playing these days because of work. If you have any suggestion please let me know.

Thanks for the report!

**Comment by purutu** [comment]
Hello, @bsides 

You can see top 8 players by setting sort type to "Number - Ascending". 
![image](https://user-images.githubusercontent.com/47320226/68330729-1536a600-0117-11ea-927d-ae876f4b6eae.png)

But, it is right-to-left order. This is not familiar to me
![image](https://user-images.githubusercontent.com/47320226/68331102-bb82ab80-0117-11ea-9c27-1bfed90b4e4c.png)

Always thanks a lot!

**Comment by Khallenis** [comment]
Thanks a lot for the heads up!

**Comment by bsides** [comment]
Does @purutu option solve it for you @Khallenis?

**Comment by Khallenis** [comment]
Yeah, solved. :)
